"""生成 CANDIDATES.md：每个候选目录 -> 谁消费了它 -> 里面每个模块的源摘要。

为什么需要：§3.7 那次误归属之所以可能，是因为"哪个文件产生了哪个测量"这件事
在仓库里没有任何地方记录。目录名（.tmp/cand、cand2、cand3、cand4、cand_fact2）
不带语义，模块名又跨目录重复，于是 `gen_default_s0` 同时指两个不同的程序。

这个脚本只做一件事：把磁盘上的事实列出来，不解释、不推断哪个是"对的"。
消费关系从各 runner/chain 脚本里 grep 出来，测量从各 screening/grid 的 raw 记录里读。
"""
import glob
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def source_of(path: Path):
    try:
        c = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None, None
    design = c.get("design")
    src = design.get("prefetcher_source") if isinstance(design, dict) else (
        c.get("source") or c.get("code"))
    return c.get("module_name") or c.get("candidate_id"), src


def consumers() -> dict:
    """directory -> set of scripts/configs that name it."""
    out = {}
    try:
        hits = subprocess.run(
            ["git", "grep", "-n", "-I", r"\.tmp/[a-z0-9_]*cand[a-z0-9_]*", "--",
             ".tmp", "scripts", "chia_loop", "results"],
            cwd=REPO, capture_output=True, text=True, timeout=120).stdout
    except Exception:
        return out
    for line in hits.splitlines():
        file = line.split(":", 1)[0]
        lineno = line.split(":")[1] if len(line.split(":")) > 1 else ""
        # finditer, not search: `--candidate-dirs .tmp/cand .tmp/cand2 .tmp/cand3
        # .tmp/cand4` is one line naming four directories, and re.search records only
        # the first -- which made three of them look unreferenced. An index of
        # provenance that under-reports is worse than no index.
        for m in re.finditer(r"\.tmp/([a-z0-9_]*cand[a-z0-9_]*)", line):
            tag = m.group(1)
            # A candidate directory referencing its own path (its generation log, a
            # sibling JSON) is not a consumer.
            if file.startswith(f".tmp/{tag}/"):
                continue
            out.setdefault(tag, set()).add(f"{file}:{lineno}")
    # Consumers that decide what a directory is *for* first: configs, then runners,
    # then case builders, then everything else.
    rank = [".tmp/cfg/", "scripts/", ".tmp/run", ".tmp/screen", ".tmp/wait",
            "chia_loop/", "results/"]
    def key(tag, ref):
        for i, p in enumerate(rank):
            if ref.startswith(p):
                return (i, ref)
        return (len(rank), ref)
    return {k: sorted(v, key=lambda r: key(k, r)) for k, v in out.items()}


def measured_by_module() -> dict:
    """module -> list of (artifact, cycles, binary, candidate_sha) from every raw record."""
    found = {}
    for rel in ("results/candidate_compile_screening_2026-09-22.jsonl",
                "results/factorial_screening_2026-09-23.jsonl",
                "results/module_effect_control_2026-09-22.jsonl",
                "results/reference_designs_2026-09-22.jsonl"):
        p = REPO / rel
        if not p.is_file():
            continue
        for line in p.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line.startswith("{"):
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            mod = d.get("module") or d.get("design")
            if mod and d.get("cycles"):
                found.setdefault(mod, []).append(
                    (rel, d["cycles"], str(d.get("binary_sha256"))[:16],
                     "cold" if d.get("incremental") is False else "incremental"))
    for rel in sorted(glob.glob(str(REPO / "results" / "grid_*" / "raw.json"))):
        raw = json.loads(Path(rel).read_text(encoding="utf-8"))
        for cell in raw.get("cells", {}).values():
            mod = cell.get("candidate_id")
            if mod:
                found.setdefault(mod, []).append(
                    (os.path.relpath(rel, REPO), cell["median"]["cycles"],
                     str(cell.get("binary_sha256", ""))[:16],
                     f"candidate_sha {str(cell.get('candidate_sha256'))[:16]}"))
    return found


def main() -> int:
    cons = consumers()
    measured = measured_by_module()

    lines = [
        "# Candidate directories, and what each one authorizes",
        "",
        "Generated by `scripts/make_candidates_index.py` -- do not hand-edit.",
        "",
        "Module names are **not** design identifiers: the same name appears in several",
        "directories with different content. One of those collisions caused a real defect",
        "(paper section 3.7): an audit case cited a source that cannot compile, while the",
        "measurement it reports came from a differently-named-but-same-module file in",
        "another directory. The join key for anything load-bearing is `candidate_sha256`",
        "or `design_sha256`, never the module name.",
        "",
    ]

    dirs = sorted(d for d in glob.glob(str(REPO / ".tmp" / "*cand*")) if os.path.isdir(d))
    lines.append("## Directories")
    lines.append("")
    lines.append("| directory | files | distinct modules | referenced by |")
    lines.append("| --- | --- | --- | --- |")
    for d in dirs:
        tag = os.path.basename(d)
        files = sorted(glob.glob(os.path.join(d, "*.json")))
        files = [f for f in files if "generation-log" not in f]
        mods = {source_of(Path(f))[0] for f in files}
        refs = cons.get(tag, [])
        shown = ", ".join(f"`{r}`" for r in refs[:4]) or "not referenced in tracked files"
        if len(refs) > 4:
            shown += f" (+{len(refs) - 4} more)"
        lines.append(f"| `.tmp/{tag}` | {len(files)} | {len(mods)} | {shown} |")

    lines += ["", "## Source digest per module, per directory", "",
              "Two directories carrying the same module name with different digests hold",
              "**different programs**. This table is the disambiguation.", "",
              "| module | directory | source sha256 (16) | chars |", "| --- | --- | --- | --- |"]
    by_module = {}
    for d in dirs:
        tag = os.path.basename(d)
        for f in sorted(glob.glob(os.path.join(d, "*.json"))):
            if "generation-log" in f:
                continue
            mod, src = source_of(Path(f))
            if not mod or not src:
                continue
            by_module.setdefault(mod, []).append(
                (tag, hashlib.sha256(src.encode()).hexdigest()[:16], len(src)))
    collided = 0
    for mod in sorted(by_module):
        rows = by_module[mod]
        if len({r[1] for r in rows}) > 1:
            collided += 1
        for tag, sha, ln in rows:
            mark = " **collides**" if len({r[1] for r in rows}) > 1 else ""
            lines.append(f"| `{mod}`{mark} | `.tmp/{tag}` | `{sha}` | {ln} |")

    lines += ["", f"{collided} module names carry more than one distinct source on disk.", "",
              "## Measurements keyed by module name", "",
              "Same-name rows below are **different designs**; only the row whose",
              "`candidate_sha256`/binary matches your source may be cited for it.", "",
              "| module | artifact | cycles | build / candidate sha | binary (16) |",
              "| --- | --- | --- | --- | --- |"]
    for mod in sorted(measured):
        for rel, cyc, binary, note in measured[mod]:
            lines.append(f"| `{mod}` | `{rel}` | {cyc:,.0f} | {note} | `{binary}` |")

    orphans = [os.path.basename(d) for d in dirs
               if not cons.get(os.path.basename(d))]
    if orphans:
        lines += ["", "## Directories nothing consumes", "",
                  "These hold real generated sources but no tracked config, script or "
                  "case names them: " + ", ".join(f"`.tmp/{o}`" for o in orphans) + ".",
                  "They are kept rather than deleted because a digest cited by an older "
                  "run may still need to be resolved against them, and deleting a "
                  "candidate directory is how a measurement becomes unanswerable "
                  "rather than merely untidy.", ""]

    lines += ["", "## Rule this exists to enforce", "",
              "Any claim of the form \"design X measured N cycles\" must name the source",
              "digest, not only the module name. Screening rows in this repository record a",
              "module name and a delivered-binary digest but **no source digest**, which is",
              "the exact gap that made section 3.7 unanswerable from the artifact; new",
              "producers should write `source_sha256` alongside `binary_sha256`.", ""]

    out = REPO / "CANDIDATES.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}: {len(dirs)} dirs, {len(by_module)} module names, "
          f"{collided} colliding, {len(measured)} modules with measurements")
    return 0


if __name__ == "__main__":
    sys.exit(main())
